on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

name: Run script

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    permissions:
        contents: write
        
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0' # The R version to download (if necessary) and use.
 
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
            packages:
               any::knitr
               any::rmarkdown
               any::jsonlite
               any::dplyr
               any::ggplot2
               any::readr
               any::lubridate
               any::forcats
               any::tidyverse
               any::data.table
               any::googledrive
               any::ggplot2
               
      - name: Run script
        run: |
          source: "R/code.R"
        shell: Rscript {0} 
          
      - name: Render document
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: gfm
          path: report.qmd

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Commit
        run: |
          git add .
          git commit -m "Updated report"
          git push origin main
